export const REGISTER_DEVICE = 'REGISTER_DEVICE';
export const SUBSCRIBE_STATION = 'SUBSCRIBE_STATION';
export const UPDATE_STATIONS = 'UPDATE_STATIONS';
export const UPDATE_STATION_PM_DATA = 'UPDATE_STATION_PM_DATA';
export const UPDATE_REALTIME_DATA = 'UPDATE_REALTIME_DATA';

export const UPDATE_COMPLAINTS = 'UPDATE_COMPLAINTS';
export const UPDATE_NEW_COMPLAINT = 'UPDATE_NEW_COMPLAINT';
